import fs from 'node:fs/promises';

const out='/Users/lgm/Documents/ChatGPT/Medicare/outputs/01a0ab2c-c289-74e3-8442-d7966be4cbe8';

export async function writeAnalysisFramework({clinicalBasis,evidenceSubjects,benchmark,items,expected}){
  const cite=id=>`[${id}](./Medicare_gender_care_bibliography.md#${id.toLowerCase()})`;
  const registry=JSON.parse(await fs.readFile('/Users/lgm/Documents/ChatGPT/Medicare/research/reference_registry.json','utf8'));
  const source=key=>{const s=benchmark.sources.find(x=>x.key===key);const r=registry.policy_sources.find(x=>x.url===s.url);if(!r)throw new Error(`Missing benchmark bibliography source: ${key}`);return cite(r.id);};
  const examples={shared:'Breast, bone, lymphatic and continence care; sexual desire',female_anatomy:'Local vaginal treatment, cervical screening and intrauterine devices',male_anatomy:'Prostate screening and penile erectile function',female_physiology:'Menopausal vasomotor treatment and contraceptive endocrine effects',male_physiology:'Treatment of documented male hypogonadism',mixed:'Male/female sling procedures, broad pelvic pain, site-dependent surgery and fertility services'};
  const lines=[
    '# Patient and physician sex/gender, anatomy and access: analysis framework',
    '',
    `Adopted ${clinicalBasis.adopted_on} at the investigator’s request. Working methods for the Medicare review and future white paper; not a completed systematic review or a finding of bias.`,
    '',
    '## Medicare as a benchmark for care in later life',
    '',
    `${benchmark.rationale} This is a choice of policy benchmark and analytic focus; Medicare eligibility or reimbursement does not itself define appropriate clinical care.`,
    '',
    '| Measure | Evidence supporting the benchmark | Interpretation |',
    '|---|---|---|',
    `| Per-person use, 2019 | Office-based physician visits per 100 people: 708.5 at ages 65+, 374.9 at ages 45–64, and 188.0 at ages 18–44. ${source('office_visits')} | Older adults used more office-based care per person than younger adult groups; these are not counts of all encounters. |`,
    `| Age distribution of spending, 2020 | Ages 65+ represented 17% of the population and 37% of all-payer personal health care spending. ${source('age_spending')} | A substantial spending concentration, rather than a majority of all care. |`,
    `| Spending per person, 2020 | $22,356 for ages 65+ versus $9,154 for ages 19–64. ${source('national_spending')} | All-payer personal health care dollars, not Medicare-only payments or service counts. |`,
    `| Medicare’s national spending role, 2024 | Medicare financed 21% of national health expenditures. ${source('national_spending')} | NHE and personal health care are different denominators; the years also differ. |`,
    '',
    `In the 2019 office-visit survey, chronic conditions were the major reason for 56.0% of visits among adults 65+ versus 37.6% among adults 18–64. This is a share of visits, not disease prevalence. ${source('office_visits')} The 2020 CMS age estimates include the pandemic period and allocated provider relief funding; they do not isolate those effects. ${source('age_spending')}`,
    '',
    `${benchmark.age_rule} Medicare can cover younger people with disability, ESRD or ALS, so enrollment must not be used as a substitute for age. ${source('eligibility')}`,
    '',
    benchmark.comparison_rule,
    '',
    `${benchmark.measurement_rule} These findings do not establish that most lifetime medical care occurs after age 65. The report’s intended inference is about equitable access in Medicare and its specified populations; extensions to other payers or ages require separate evidence.`,
    '',
    '**Draft rationale for the white paper:** We use Medicare as a national policy benchmark for evaluating sex-based equity in access to clinically indicated care in later life, a period characterized by substantial chronic illness and healthcare use. We will analyze coverage, payment and realized access relative to clinical need, distinguishing shared body systems from reproductive anatomy and physiology. We will identify age and entitlement groups separately and retain younger Medicare beneficiaries within the review’s existing eligibility scope.',
    '',
    '## Whose sex/gender is analyzed?',
    '',
    'Added September 16, 2026 at the investigator’s request. Patient sex/gender and physician sex/gender are separate variables. Neither is inferred from procedure anatomy, specialty or the sex/gender of interview respondents. This classification is independent of clinical basis and primary-synthesis eligibility.',
    '',
    '| Analytic subject | What the category contains | Active records |',
    '|---|---|---:|',
    ...evidenceSubjects.groups.map(g=>`| ${g.label} | ${g.description} | ${expected.analyticSubjects[g.label]} |`),
    '',
    'These are selected-record counts, not estimates of bias. Patient-care evidence includes studies within one eligible population and is not automatically a between-sex comparison. Code or specialty valuation is distinct from a measured patient-sex effect. Physician evidence remains a contextual stream outside the primary patient-sex disparity synthesis.',
    '',
    `**Patient question:** How do coverage, costs and access differ with patient sex/gender and clinical need? ${cite('L-G04')} and ${cite('L-H01')} contain direct patient-sex comparisons in the current extraction; eligibility and historical applicability still require review. ${cite('L-Q01')} addresses perceived patient barriers through clinician interviews, not physician payment.`,
    '',
    `**Physician question:** How do payments differ by the treating physician’s sex/gender? ${cite('L-C01')}, ${cite('L-C02')} and ${cite('L-C03')} belong here. The surgeon article ${cite('L-C03')} reports annual and CPT-matched payment differences; unavailable modifiers limit identical-service inference. Its null colorectal payment-per-service result is retained. Physician payments do not measure salary or patient coverage.`,
    '',
    '**Joint question:** When studies analyze both patient and physician sex/gender, extract both measurements, main effects and any concordance or interaction estimate separately. Do not substitute a clinician effect for a patient effect, or infer that one causes the other. Record author terminology, measurement source, unit of analysis and uncertainty. Future joint analyses will require their own extraction and cannot be inferred from the current physician-payment studies.',
    '',
    '## Distinctions used in the analysis',
    '',
    'We distinguish the clinical basis of care from the population named in a policy or study. Shared anatomy can have sex differences in disease burden, treatment response and access. Reproductive anatomy and reproductive physiology require their own clinical comparisons. A drug label limited to women, a screening rule naming women, and a female-specific organ are different facts. Sex/gender measurement and the existing population eligibility rules remain separate from this classification.',
    '',
    `The general clinical framework is informed by ${cite('L-B01')}. Guidance sources C-001–C-004 support specific classification decisions. The categories are review-team analytic assignments, not CMS benefit classifications.`,
    '',
    '| Clinical basis | Working definition | Examples | Selected rows |',
    '|---|---|---|---:|',
    ...clinicalBasis.groups.map(g=>`| ${g.label} | ${g.definition} | ${examples[g.id]} | ${expected.clinicalBasis[g.label]} |`),
    '',
    `Total: ${items.length} selected care-item/indication rows. Each row contributes once. Counts are not patient prevalence, counts of unique billing codes, national coverage rates or estimates of discrimination. Mixed rows can contain several services.`,
    '',
    '## How comparisons will be made',
    '',
    '**Shared conditions and systems.** Compare women and men with comparable clinical need within the same condition, service, setting and policy period, including people who do not receive care. Assess clinical eligibility independently of reimbursement eligibility; otherwise benefit exclusions and unmet need could disappear from the denominator. Extract severity and contraindications alongside coverage rules, reimbursement per service, patient spending, denials, delays and unmet need. Sex-defined clinical indications can be examined within the eligible population and against appropriate alternatives without an off-label opposite-sex comparator. Do not assume identical need or treatment response simply because the organ is shared.',
    '',
    '**Reproductive anatomy and physiology.** Assess the consistency of coverage and valuation with clinical benefit, alternatives, treatment burden and medical necessity. A service does not need an opposite-sex counterpart to warrant equitable coverage. Where procedures are compared across anatomies, justify their matching by purpose, work, time, complexity, setting and postoperative care. Preserve findings of parity and contradictory results. The differing comparisons in '+cite('L-P01')+' and '+cite('L-P02')+' illustrate why pair selection and resource adjustment matter.',
    '',
    '**Mixed and underspecified services.** Split the analysis by organ/site, diagnosis, indication and procedure code before making a sex-specific estimate. Retain the existing umbrella row for traceability until enough detail supports subdivision. Do not copy an umbrella coverage label onto every component without verification.',
    '',
    '**Policy and causal interpretation.** Keep national Medicare rules, contractor decisions and plan implementation separate. Evaluate explicit sex distinctions and unequal effects of formally neutral rules. Prespecify whether utilization and service mix are confounders, mediators or outcomes; adjustment should not silently erase a proposed mechanism. Differences alone do not identify their cause.',
    '',
    '## Decisions that prevent misclassification',
    '',
    `- Breast anatomy is shared. Mammography’s recorded women-specific screening pathway and the concentration of breast-care research in women are separate eligibility and population features. Gynecomastia is a male-associated indication involving shared breast tissue. ${cite('C-001')}`,
    `- Bone health and pelvic-floor treatment involve shared systems. The estrogen-deficiency route to bone testing remains flagged as a sex-specific policy feature; it is not reclassified as an exclusively female organ. ${cite('C-003')}, ${cite('C-004')}`,
    '- Menopause is classified as reproductive physiology. Systemic estradiol plus progestogen retains its additional uterus/endometrial-protection requirement. Local vaginal treatment is classified by its anatomical target. Classification applies to the recorded indication, not every use of estradiol or testosterone.',
    '- Sexual desire is a shared function. The recorded women-specific indications for flibanserin and bremelanotide are maintained separately from anatomy, including the applicable label year. The erectile-dysfunction sildenafil row is indication-specific; other uses would need their own coverage review.',
    `- Endometriosis surgery is site-dependent because lesions can involve reproductive organs and shared sites. The broad prolapse row remains provisionally mixed until the organ and repair codes are identified. These classifications do not deny the female-predominant clinical burden. ${cite('C-002')}`,
    '',
    '## Proposed white-paper reporting structure',
    '',
    '1. Methods: report this dated analytic amendment, separate patient and physician sex/gender variables, study units, the six clinical categories, population screening and indication-level coding. State that the classification was added during the ongoing review rather than prospectively registered.',
    '2. Results on shared conditions: report sex differences in clinically appropriate access, patient spending, coverage restrictions and comparable-service payments.',
    '3. Results on reproductive anatomy and physiology: report organ- or indication-specific coverage and valuation, clinically justified cross-service comparisons, and services without a direct counterpart.',
    '4. Mixed services and unresolved comparisons: identify the information needed for component-level analysis instead of combining incompatible procedures.',
    '5. Separate contextual section: report physician-gender payment evidence, annual versus per-service outcomes and matching limitations. Do not pool these effects with patient comparisons. Identify patient–physician interaction results separately when available.',
    '6. Discussion: distinguish anatomical/physiological need, unequal burden, policy design and evidence supporting inequity. Explain uncertainty, limitations and null findings.',
    '',
    `Kidney care in ${cite('L-Q01')} illustrates a shared-system access question. Its clinician interviews are qualitative context, not a Medicare reimbursement estimate; it does not add a dialysis coverage row to the current inventory. Clinician-payment studies ${cite('L-C01')}, ${cite('L-C02')} and ${cite('L-C03')} remain separate from patient-sex comparisons.`,
    '',
    '## Draft Methods paragraph',
    '',
    '> We recorded the analytic subject, unit, patient sex/gender role, physician sex/gender role, comparison axis and inference boundary for each active study. Physician-gender findings are maintained separately from the primary patient-sex synthesis; studies within one population and code-level comparisons are not automatically treated as direct patient-sex contrasts. We classified each care-item/indication by its clinical basis: shared body systems or functions; female reproductive anatomy; male reproductive anatomy; female reproductive physiology; male reproductive physiology; or mixed/site-dependent services. We separately recorded sex-defined eligibility, relevant physiology and the population represented in the evidence. Planned comparisons for shared conditions will examine women and men with comparable clinical need, including those who did not receive care. Clinical need will be assessed independently of reimbursement eligibility. For reproductive anatomy or physiology, we will assess clinical need and policy consistency without requiring an opposite-sex counterpart; any cross-procedure comparison will require explicit justification of clinical and resource comparability. Bundled services remain unresolved pending component-level extraction. Inventory counts are descriptive and are not interpreted as national coverage rates or causal evidence of reimbursement bias.',
    '',
    '## Maintenance and sources',
    '',
    'Item-level classifications, explanations and comparison approaches appear in Data & Targets, columns U–X. The dashboard summarizes clinical basis against coverage status. The canonical clinical classification file is research/clinical_basis.json. Literature columns S–X and research/evidence_subjects.json retain study subject and variable roles. The dashboard shows these study counts separately. Coverage findings are unchanged by classification alone.',
    '',
    'See the [living bibliography](./Medicare_gender_care_bibliography.md) for all stable reference IDs and source links. Scientific evidence, clinical classification guidance and Medicare policy sources remain separately identified.',
    ''
  ];
  await fs.writeFile(`${out}/Medicare_anatomy_physiology_analysis_framework.md`,lines.join('\n'));
}
